### ISSUE TITLE
[Feature Request] Kill process by port number

### ISSUE THREAD

**Issue by Cierra-Runis** [8LWXpg/PowerToysRun-ProcessKiller#10]
### Description

Sometime we reopen a backend server but it doesn't release the port it used, can it be killed by the port it used?

### Use case

As above.

**Comment by 8LWXpg** [comment]
A process can take multiple ports, how to present that in title so that it's searchable in that case?

**Comment by Cierra-Runis** [comment]
```
kl --port 8080

1. Kill all process listening port 8080
2. ProcessName1 PID1
3. ProcessName2 PID2
```

Maybe like this.
