### ISSUE TITLE
[Enhancement] allow shell's explorer.exe to be killed (or restarted)

### ISSUE THREAD

**Issue by oliverrahner** [8LWXpg/PowerToysRun-ProcessKiller#14]
### Description

I understand that the `explorer.exe` that hosts the Windows shell is explicitly excluded.
The use case that made me search for something like this plugin was exactly this: needing to restart the shell explorer regularly.

My suggestion would be to
* make explorer.exe addressable optionally and/or
* treat the shell explorer.exe process specifically by not only killing it, but restarting it at the same time

Or are we looking at a permissions issue here that makes this impossible?

**Comment by 8LWXpg** [comment]
It's already mentioned at #5 implemented at #7. Do you have "Run each explorer window in its own process" setting enabled or using older versions?

**Comment by 8LWXpg** [comment]
Ok, I think I misunderstood that, you need the ability to kill `explorer.exe` that hosts Windows shell. But needless to say, you're in bigger issue if you need to kill explorer regularly.

**Comment by oliverrahner** [comment]
Just to provide background, the issue why I need to restart explorer is rather minor: Sometimes when maximizing windows, the size of the taskbar isn't taken into account, so the lower end of the windows ends up behind the taskbar. When restarting explorer, this gets "repaired".
And I agree that I should probably investigate the root cause of this issue. But then, I have seen a lot of these small annoyances over the past years that I stopped caring about root causes, which might come and go eventually, and instead look for efficient workarounds.

That being said, I'd argue that you would just be providing a shortcut to a feature that Windows already offers:

![image](https://github.com/user-attachments/assets/f7e99705-ddf2-4a0b-937b-78b80b9b8550)

![image](https://github.com/user-attachments/assets/041f0252-0fd1-4e51-b820-fe4bde854af7)

I'm referring to the "End task" button switching to "Restart task" instead when selecting the explorer process.

**Comment by oliverrahner** [comment]
Much appreciated :)
