### ISSUE TITLE
DLL has wrong version information

### ISSUE THREAD

**Issue by htcfreek** [8LWXpg/PowerToysRun-ProcessKiller#18]
### Description

The version information of the DLL file are wrong.

Please note that we are working on an improvement for the plugin manager user interface that will show the `File version` as plugin version.

![image](https://github.com/user-attachments/assets/e73f7325-fa6e-4010-aee7-42a33989e342)

![image](https://github.com/user-attachments/assets/25bd6519-6cb5-404a-be89-51054209e0b7)

### Steps to reproduce

View file properties.

**Comment by htcfreek** [comment]
@8LWXpg 
Did you publish the wrong assets for 1.9.0? The JSON still shows 1.8.1 and the DLL still shows 1.0.0.

**Comment by 8LWXpg** [comment]
Forgot to change release script to .net9, will make a quick fix.

**Comment by htcfreek** [comment]
Perfect. Now it is as expected.
