### ISSUE TITLE
Add plugin to official third-party plugin list

### ISSUE THREAD

**Issue by htcfreek** [8LWXpg/PowerToysRun-ProcessKiller#2]
There is a document that lists third-party plugins for PT Run. It is linked from the PT Settings Ui.

File: https://github.com/microsoft/PowerToys/blob/main/doc%2FthirdPartyRunPlugins.md

I suggest to add your plugin on the list.

**Comment by 8LWXpg** [comment]
https://github.com/microsoft/PowerToys/pull/33830
