### ISSUE TITLE
[Enhancement] Tooltip for the results

### ISSUE THREAD

**Issue by htcfreek** [8LWXpg/PowerToysRun-ProcessKiller#4]
### Description

Add a tool tip that shows the full path and additionally the command line of the process.

![image](https://github.com/user-attachments/assets/bdf25ede-b1ae-4ab1-a8e8-8981d4dc7d54)

### Use case

This helps to better identify the process.

**Comment by htcfreek** [comment]
And main window title might be helpful too.

**Comment by htcfreek** [comment]
@8LWXpg 
Are you okay if I submit a small PR the next days to improve the new tool tip?

I like to add/show:
- Path (Long paths are cut off in result subtitle.)
- Main window name. (Can help identify the process.)
- Command line only if setting is enabled.

_If you are okay with it feel free to open a new issue and assign me._

**Comment by 8LWXpg** [comment]
Always welcome.

**Comment by htcfreek** [comment]
@8LWXpg 
Any plans to publish a new release containing the last changes?

**Comment by 8LWXpg** [comment]
I will, as soon as I have free time
