### ISSUE TITLE
[Enhancement] Exclude only Shell process instead of all Explorer processes 

### ISSUE THREAD

**Issue by htcfreek** [8LWXpg/PowerToysRun-ProcessKiller#5]
Currently all explorer processes are blocked for killing as system process.

Instead it is possible to only block the process if it hosts the Windows Shell.

In combination with the System setting "Run each explorer window in its own process" this allows killing `Explorer.exe`.

```csharp
/// <summary>
        /// Gets a value indicating whether this is the shell process or not
        /// The shell process (like explorer.exe) hosts parts of the user interface (like taskbar, start menu, ...)
        /// </summary>
        internal bool IsShellProcess
        {
            get
            {
                IntPtr hShellWindow = NativeMethods.GetShellWindow();
                return GetProcessIDFromWindowHandle(hShellWindow) == ProcessID;
            }
        }

        /// <summary>
        /// Gets the process ID for the window handle
        /// </summary>
        /// <param name="hwnd">The handle to the window</param>
        /// <returns>The process ID</returns>
        internal static uint GetProcessIDFromWindowHandle(IntPtr hwnd)
        {
            _ = NativeMethods.GetWindowThreadProcessId(hwnd, out uint processId);
            return processId;
        }
```

**Comment by 8LWXpg** [comment]
Are you willing to submit a PR for this? I'm asking because you’ve already provided a basic fix here.

**Comment by htcfreek** [comment]
Can do this. But the next weeks I don't have the time to work on it. So it will take some time to create the PR.

_(The code snippets are copied from the PT Run Window Walker plugin code. The native methods used in the snippets are defined in `Wox.Plugin.Common.Win32`. You can add this class as using in your code.)_
