### ISSUE TITLE
'Fail to initialize plugins'

### ISSUE THREAD

**Issue by AstudilloMarillo** [8LWXpg/PowerToysRun-ProcessKiller#8]
### Description

I'm getting the 'Fail to initialize plugins' message whenever I start PowerToys with this plugin in the Plugins folder. I can click 'OK' and use PowerToys, but the ProcessKiller plugin doesn't work. Any way to fix this?

![image](https://github.com/user-attachments/assets/1c553c19-7e01-482f-8690-bfa8fb8f58a2)

**Comment by 8LWXpg** [comment]
I can't replicate this issue, are you using Windows on ARM?

**Comment by AstudilloMarillo** [comment]
> I can't replicate this issue, are you using Windows on ARM?

No I'm not, just regular Windows.
PowerToys v0.79.0
I have several (third party) plugins for PowerToys Run, but only get this message with this plugin. 

Any more information I can give you?

**Comment by 8LWXpg** [comment]
Well, I don't have any ideas then. Maybe try to update PowerToys and hope it works?

**Comment by AstudilloMarillo** [comment]
> Maybe try to update PowerToys and hope it works?

Oh what... I thought I was on the latest version because 'check for updates' said PowerToys was up-to-date. I manually updated, and now the plugin works great! Weird that the update checker wasn't working, but I'm really glad the plugin now works! :)
